#!/usr/bin/env node
/**
 * hashJS precompiler.
 *
 * Turns template files into a plain .js file containing the render functions
 * they compile to. Load that file in the page and pair it with
 * hashJS.fromPrecompiled, and nothing is ever evaluated in the browser — so a
 * Content Security Policy needs no 'unsafe-eval'.
 *
 *   node precompile.js templates/ -o public/templates.js
 *   node precompile.js a.html b.html -o out.js --global MyTemplates
 *
 * Each template becomes a property named after its file, without extension.
 *
 * The output uses `with`, which is a syntax error in strict mode, so the
 * generated file must be loaded as a classic script — not as a module and not
 * under "use strict".
 */

'use strict';

const fs = require('fs');
const path = require('path');
const hashJS = require('./hashJS.js');

const TEMPLATE_EXTENSIONS = ['.html', '.htm', '.hashjs', '.hjs', '.tpl'];

function usage(message) {
    if (message) { console.error('precompile: ' + message + '\n'); }
    console.error('Usage: node precompile.js <file|dir>... [-o out.js] [--global NAME]');
    console.error('');
    console.error('  -o, --out FILE   where to write (default: stdout)');
    console.error('      --global N   global to hang the templates off (default: hashJSTemplates)');
    process.exit(message ? 1 : 0);
}

function parseArgs(argv) {
    const inputs = [];
    let out = null;
    let globalName = 'hashJSTemplates';

    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '-h' || a === '--help') { usage(); }
        else if (a === '-o' || a === '--out') { out = argv[++i]; if (!out) { usage('-o needs a filename'); } }
        else if (a === '--global') { globalName = argv[++i]; if (!globalName) { usage('--global needs a name'); } }
        else if (a.startsWith('-')) { usage('unknown option ' + a); }
        else { inputs.push(a); }
    }
    if (inputs.length === 0) { usage('no input files'); }
    return { inputs, out, globalName };
}

// Expand directories one level into the template files they hold.
function collect(inputs) {
    const files = [];
    for (const input of inputs) {
        let stat;
        try { stat = fs.statSync(input); }
        catch (e) { usage('cannot read ' + input); }

        if (stat.isDirectory()) {
            for (const name of fs.readdirSync(input).sort()) {
                if (TEMPLATE_EXTENSIONS.includes(path.extname(name).toLowerCase())) {
                    files.push(path.join(input, name));
                }
            }
        } else {
            files.push(input);
        }
    }
    if (files.length === 0) { usage('no template files found'); }
    return files;
}

function main() {
    const { inputs, out, globalName } = parseArgs(process.argv.slice(2));
    const files = collect(inputs);

    const seen = new Map();
    const entries = [];
    let failures = 0;

    for (const file of files) {
        const key = path.basename(file, path.extname(file));
        if (seen.has(key)) {
            console.error('precompile: two templates would both be named "' + key + '":');
            console.error('  ' + seen.get(key));
            console.error('  ' + file);
            failures++;
            continue;
        }
        seen.set(key, file);

        const source = fs.readFileSync(file, 'utf8');
        let compiled;
        try {
            compiled = hashJS.precompile(source);
        } catch (e) {
            console.error('precompile: ' + file + ' -> ' + e.message);
            failures++;
            continue;
        }

        // Compile-check the emitted source here rather than in the browser,
        // where there would be nothing useful to report it against.
        try {
            new Function('return (' + compiled + ')');
        } catch (e) {
            console.error('precompile: ' + file + ' produced invalid JavaScript -> ' + e.message);
            console.error('  usually an unclosed #{ … }# or a stray # in the template');
            failures++;
            continue;
        }

        entries.push('    ' + JSON.stringify(key) + ': ' + compiled);
    }

    if (failures > 0) {
        console.error('\nprecompile: ' + failures + ' template(s) failed, nothing written');
        process.exit(1);
    }

    const banner = '/* Generated by hashJS precompile from ' + entries.length +
                   ' template(s). Do not edit.\n' +
                   '   Load as a classic script: the code below uses `with`, which is\n' +
                   '   illegal in strict mode and therefore in modules. */\n';

    const body = banner +
        '(function (root) {\n' +
        '  root[' + JSON.stringify(globalName) + '] = {\n' +
        entries.join(',\n') + '\n' +
        '  };\n' +
        '})(typeof window !== "undefined" ? window : globalThis);\n';

    if (out) {
        fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
        fs.writeFileSync(out, body, 'utf8');
        console.error('precompile: wrote ' + entries.length + ' template(s) to ' + out);
    } else {
        process.stdout.write(body);
    }
}

main();
